#include <stdio.h>
#include <stdlib.h>
char flag[63];

void func_0(char* a1);
void func_1(char* a1);
void func_2(char* a1);
void func_3(char* a1);
void func_4(char* a1);
void func_5(char* a1);
void func_6(char* a1);
void func_7(char* a1);
void func_8(char* a1);
void func_9(char* a1);
void func_10(char* a1);
void func_11(char* a1);
void func_12(char* a1);
void func_13(char* a1);
void func_14(char* a1);
void func_15(char* a1);
void func_16(char* a1);
void func_17(char* a1);
void func_18(char* a1);
void func_19(char* a1);
void func_20(char* a1);
void func_21(char* a1);
void func_22(char* a1);
void func_23(char* a1);
void func_24(char* a1);

int main(){
    asm(".intel_syntax noprefix\n");
    scanf("%50s", flag);
    func_0(flag);
    printf("The flag is %s", flag);
    return 0;
}

void func_9(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_9\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_9:\n\t"
	);
	func_10(a1 + 1);
	return;
}

void func_13(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_13\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_13:\n\t"
	);
	func_14(a1 + 1);
	return;
}

void func_10(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_10\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_10:\n\t"
	);
	func_11(a1 + 1);
	return;
}

void func_20(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_20\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_20:\n\t"
	);
	func_21(a1 + 1);
	return;
}

void func_14(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_14\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_14:\n\t"
	);
	func_15(a1 + 1);
	return;
}

void func_23(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_23\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_23:\n\t"
	);
	func_24(a1 + 1);
	return;
}

void func_7(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_7\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_7:\n\t"
	);
	func_8(a1 + 1);
	return;
}

void func_1(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_1\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_1:\n\t"
	);
	func_2(a1 + 1);
	return;
}

void func_21(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_21\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_21:\n\t"
	);
	func_22(a1 + 1);
	return;
}

void func_11(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_11\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_11:\n\t"
	);
	func_12(a1 + 1);
	return;
}

void func_16(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_16\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_16:\n\t"
	);
	func_17(a1 + 1);
	return;
}

void func_6(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_6\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_6:\n\t"
	);
	func_7(a1 + 1);
	return;
}

void func_3(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_3\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_3:\n\t"
	);
	func_4(a1 + 1);
	return;
}

void func_24(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_24\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_24:\n\t"
	);
	return;
}

void func_8(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_8\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_8:\n\t"
	);
	func_9(a1 + 1);
	return;
}

void func_17(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_17\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_17:\n\t"
	);
	func_18(a1 + 1);
	return;
}

void func_12(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_12\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_12:\n\t"
	);
	func_13(a1 + 1);
	return;
}

void func_19(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_19\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_19:\n\t"
	);
	func_20(a1 + 1);
	return;
}

void func_22(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_22\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_22:\n\t"
	);
	func_23(a1 + 1);
	return;
}

void func_18(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_18\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_18:\n\t"
	);
	func_19(a1 + 1);
	return;
}

void func_2(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_2\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_2:\n\t"
	);
	func_3(a1 + 1);
	return;
}

void func_0(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_0\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_0:\n\t"
	);
	func_1(a1 + 1);
	return;
}

void func_4(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"nop\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_4\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_4:\n\t"
	);
	func_5(a1 + 1);
	return;
}

void func_15(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_15\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_15:\n\t"
	);
	func_16(a1 + 1);
	return;
}

void func_5(char* a1){
	__asm__ __volatile__ (
		"lea rbx, [rip + 7]\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"dec ebx\n\t"
		"inc ebx\n\t"
		"inc ebx\n\t"
		"lea rax, [rip + 0]\n\t"
		"sub rax, rbx\n\t"
		"cmp al, byte ptr [rdi]\n\t"
		"je END_5\n\t"
		"push 0x3c\n\t"
		"pop rax\n\t"
		"syscall\n\t"
		"END_5:\n\t"
	);
	func_6(a1 + 1);
	return;
}

